apiVersion: rabbitmq.com.rabbitmq.com/v1beta1
kind: OperatorPolicy
metadata:
  labels:
    app.kubernetes.io/name: messaging-topology-operator
    app.kubernetes.io/managed-by: kustomize
  name: operatorpolicy-sample
spec:
  # TODO(user): Add fields here
