apiVersion: rabbitmq.com.rabbitmq.com/v1alpha1
kind: SuperStream
metadata:
  labels:
    app.kubernetes.io/name: messaging-topology-operator
    app.kubernetes.io/managed-by: kustomize
  name: superstream-sample
spec:
  # TODO(user): Add fields here
