# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/rabbitmq.com_queues.yaml
- bases/rabbitmq.com_exchanges.yaml
- bases/rabbitmq.com_bindings.yaml
- bases/rabbitmq.com_users.yaml
- bases/rabbitmq.com_vhosts.yaml
- bases/rabbitmq.com_policies.yaml
# +kubebuilder:scaffold:crdkustomizeresource

configurations:
- kustomizeconfig.yaml
