#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! Matching by Deployment is acceptable because we have only one Deployment :-)
#@overlay/match by=overlay.subset({"kind": "Deployment"})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
        - name: #@ data.values.pull_secret_name