
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: federations.rabbitmq.com
spec:
  group: rabbitmq.com
  names:
    categories:
    - all
    kind: Federation
    listKind: FederationList
    plural: federations
    singular: federation
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Federation is the Schema for the federations API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: 'FederationSpec defines the desired state of Federation For
              how to configure federation upstreams, see: https://www.rabbitmq.com/federation-reference.html.'
            properties:
              ackMode:
                enum:
                - on-confirm
                - on-publish
                - no-ack
                type: string
              exchange:
                type: string
              expires:
                type: integer
              maxHops:
                type: integer
              messageTTL:
                type: integer
              name:
                description: Required property; cannot be updated
                type: string
              prefetch-count:
                type: integer
              queue:
                type: string
              rabbitmqClusterReference:
                description: Reference to the RabbitmqCluster that the exchange will
                  be created in. Required property.
                properties:
                  name:
                    description: Cannot be updated
                    type: string
                required:
                - name
                type: object
              reconnectDelay:
                type: integer
              trustUserId:
                type: boolean
              uri:
                description: The AMQP URI(s) for the upstream. Required property.
                type: string
              vhost:
                default: /
                description: Default to vhost '/'; cannot be updated
                type: string
            required:
            - name
            - rabbitmqClusterReference
            - uri
            type: object
          status:
            description: FederationStatus defines the observed state of Federation
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: The last time this Condition type changed.
                      format: date-time
                      type: string
                    message:
                      description: Full text reason for current status of the condition.
                      type: string
                    reason:
                      description: One word, camel-case reason for current status
                        of the condition.
                      type: string
                    status:
                      description: True, False, or Unknown
                      type: string
                    type:
                      description: Type indicates the scope of RabbitmqCluster status
                        addressed by the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: observedGeneration is the most recent successful generation
                  observed for this Federation. It corresponds to the Federation's
                  generation, which is updated on mutation by the API Server.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
